name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_frontend_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build front-end-nextjs --file front-end-nextjs/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/qr-code-app:latest
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/qr-code-app:latest

  build_api_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the second Docker image
      run: docker build api --file api/Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/qr-code-app-api:latest
    - name: Push the second Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/qr-code-app-api:latest